grraghav120/expense-tracker

backend/app.js
backend/models/userModel.js
backend/routes/expense.js
backend/routes/user.js
package-lock.json
package.json
src/app/auth/auth.service.ts
src/app/component/login/login.component.html
src/app/component/login/login.component.ts
src/app/component/profile/profile.component.ts
src/app/component/signup/signup.component.ts
src/app/component/view-expenses/view-expenses.component.ts
src/app/services/business-data.service.ts

login done

---

src/app/app.component.ts
src/app/auth/auth.service.ts

After Refresh no logout no again login.
Logout only after 1 hr or manually

persist the state of user

---

backend/routes/expense.js
src/app/auth/auth.service.ts
src/app/component/view-expenses/view-expenses.component.ts

issue resolve Last Login Date

---

src/app/component/profile/profile.component.html
src/app/component/profile/profile.component.scss
src/app/component/profile/profile.component.ts

profile dates are fixed

---

backend/models/userModel.js
backend/routes/expense.js
src/app/app.module.ts
src/app/auth/auth.service.ts
src/app/component/profile/profile.component.html
src/app/component/profile/profile.component.ts
src/app/component/view-expenses/view-expenses.component.html
src/app/component/view-expenses/view-expenses.component.ts

profile progress bar and paginator

---

backend/app.js
src/app/app.module.ts
src/app/component/view-expenses/confirm.html
src/app/component/view-expenses/view-expenses.component.ts
src/app/component/view-single/view-single.component.html
src/app/component/view-single/view-single.component.scss
src/app/component/view-single/view-single.component.ts

View Expense Functionlality

---

src/app/app.module.ts
src/app/component/header/header.component.html
src/app/component/header/header.component.ts
src/app/component/loader/loader.component.html
src/app/component/loader/loader.component.scss
src/app/component/loader/loader.component.ts
src/app/component/view-expenses/view-expenses.component.html
src/app/component/view-expenses/view-expenses.component.ts

Logger implement

---

backend/app.js
src/app/component/add-expense/add-expense.component.html
src/app/component/add-expense/add-expense.component.ts
src/app/component/signup/signup.component.html
src/app/component/signup/signup.component.ts

errors and patterns

---

backend/app.js
backend/routes/expense.js
src/app/auth/auth.service.ts
src/app/component/profile/profile.component.html
src/app/component/profile/profile.component.ts

Profile Name and Username

---

src/app/auth/auth.service.ts
src/app/component/alert-box/alert-box.component.html
src/app/component/alert-box/alert-box.component.ts
src/app/component/dashboard/dashboard.component.html
src/app/component/header/header.component.html
src/app/component/header/header.component.ts
src/app/component/home/home.component.ts
src/app/component/import/import.component.html
src/app/component/import/import.component.scss
src/app/component/import/import.component.ts
src/app/component/view-expenses/view-expenses.component.html
src/app/component/view-expenses/view-expenses.component.ts
src/app/services/business-data.service.ts

import functionlity done

---

package-lock.json
package.json
src/app/app.module.ts
src/app/auth/auth.service.ts
src/app/component/add-category/add-category.component.html
src/app/component/add-category/add-category.component.ts
src/app/component/add-expense/add-expense.component.html
src/app/component/add-expense/add-expense.component.ts
src/app/component/header/header.component.html
src/app/component/import/import.component.html
src/app/component/import/import.component.ts
src/app/component/login/login.component.html
src/app/component/login/login.component.ts
src/app/component/signup/signup.component.html
src/app/component/signup/signup.component.ts
src/app/component/view-expenses/confirm.html
src/app/component/view-expenses/view-expenses.component.ts
src/environments/environment.development.ts
src/environments/environment.prod.ts

Import functionality

---

src/app/component/add-expense/add-expense.component.html
src/app/component/add-expense/add-expense.component.ts

Bug On Update Fix

---

src/app/component/welcome/welcome.component.html
src/app/component/welcome/welcome.component.ts

issue fixed 72

---

src/app/app-routing.module.ts
src/app/component/header/header.module.ts
src/app/component/home/home.module.ts
src/app/component/welcome/welcome.module.ts

add title on pages

---

src/app/component/header/add-expense/add-expense.component.html
src/app/component/header/add-expense/add-expense.component.scss
src/app/component/header/add-expense/add-expense.component.ts
src/app/component/home/view-single/view-single.component.html
src/app/component/home/view-single/view-single.component.ts

fix comment issue in viewpagw

---

backend/routes/user.js
src/app/auth/auth.service.ts
src/app/shared/alert-box/alert-box.component.html
src/app/shared/alert-box/alert-box.component.ts
src/app/shared/profile/profile.component.html
src/app/shared/profile/profile.component.ts

add delete functionality

---

src/app/shared/alert-box/alert-box.component.html
src/app/shared/alert-box/alert-box.component.ts

account abc

---

src/app/component/welcome/login/login.component.html

Updated Typo in Expense Tracker Login page

---

src/app/component/home/view-expenses/view-expenses.component.ts
src/app/component/home/view-single/view-single.component.html
src/app/component/home/view-single/view-single.component.ts
src/app/component/welcome/login/login.component.html
src/app/component/welcome/login/login.component.scss
src/app/component/welcome/signup/signup.component.html
src/app/component/welcome/signup/signup.component.scss
src/app/shared/welcome-loader/welcome-loader.component.html
src/app/shared/welcome-loader/welcome-loader.component.scss

solve issue 87

---

backend/routes/user.js
src/app/component/home/home.component.html
src/app/component/home/home.component.ts
src/app/component/home/view-expenses/view-expenses.component.html
src/app/component/home/view-expenses/view-expenses.component.scss
src/app/component/home/view-expenses/view-expenses.component.ts
src/app/component/welcome/welcome.component.html
src/app/component/welcome/welcome.component.ts
src/app/services/business-data.service.ts

Create a new API

---

src/app/app.component.ts
src/app/auth/auth-interceptor.ts
src/app/auth/auth.service.ts
src/app/component/header/header.component.ts
src/app/component/home/home.component.html
src/app/component/home/home.component.ts
src/app/component/home/view-expenses/view-expenses.component.ts
src/app/component/welcome/welcome.component.ts
src/app/services/business-data.service.ts
src/app/shared/alert-box/alert-box.component.html
src/app/shared/alert-box/alert-box.component.ts
src/app/shared/footer/footer.component.html
src/app/shared/footer/footer.component.ts

local to session storage and some changes to version

---

backend/routes/expense.js
src/app/component/header/add-category/add-category.component.html
src/app/component/header/add-category/add-category.component.ts
src/app/services/business-data.service.ts
src/app/shared/profile/profile.component.html
src/app/shared/profile/profile.component.ts

Finally completed
to do this needed to make an API for edit the categories and save them 
That's all
Closes #40

Edit Categories 

---

backend/routes/expense.js
backend/routes/user.js

admin_panel complete

---

.gitignore
angular.json
src/app/auth/auth.service.ts
src/app/services/business-data.service.ts
src/app/shared/alert-box/alert-box.component.html
src/app/shared/alert-box/alert-box.component.scss
src/app/shared/alert-box/alert-box.component.ts
src/app/shared/rating/rating.component.html
src/app/shared/rating/rating.component.scss
src/app/shared/rating/rating.component.spec.ts
src/app/shared/rating/rating.component.ts
src/app/shared/shared.module.ts
src/environments/environment.development.ts
src/environments/environment.ts

closed #104 
closed #103 
closed #102

Feedback Feature release
